object Ver {
    const val coroutinesAndroid = "1.5.1"
    const val annotation = "1.2.0"
    const val ktx = "1.6.0"
    const val constraintlayout = "2.0.4"
    const val lifecycle = "2.3.1"
    const val recyclerview = "1.2.1"
    const val room = "2.3.0"
    const val moshi = "1.12.0"
    const val wearMsger = "2.0.2"
    const val timber = "5.0.0"
    const val appcompat = "1.3.1"
    const val nav = "2.3.5"
    const val viewpager2 = "1.0.0"
    const val fragment = "1.3.6"
    const val preference = "1.1.1"
    const val koin = "3.1.2"
    const val material = "1.4.0"
    const val materialIntro = "2.0.0"
    const val subsamplingImageView = "3.10.0"
    const val palette = "1.0.0"
    const val exifinterface = "1.3.2"
    const val appCenter = "4.1.0"


    // test
    const val test = "1.4.0"
    const val strikt = "0.31.0"
    const val junit = "4.13.2"
}